version: "3"
services:
    frontend:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - backend

    backend:
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        depends_on:
            - database

    database:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/url-shortener

volumes:
    mongodb_data:
